module Explorer.Stubs exposing (..)


blockSummaryStubs =
    [ ( "allTransactions: The most comprehensive transactions example we have, mostly generated by the `debugTestFullProvision` helper function in middleware, with some manual additional transaction types added. Includes example of finalization record."
      , getBlockSummaryAllTransactionsStub
      )
    , ( "sc module deploys: example from the SC demo", getBlockSummaryContractDeploysStub )
    , ( "failure", getBlockSummaryFailureStub )
    , ( "rstub", getBlockSummaryResponseStub )
    ]


getBlockSummaryAllTransactionsStub =
    """
{
  "specialEvents": [
    {
      "bakerId": 1,
      "rewardAmount": 12463,
      "bakerAccount": "3siDnxannkQYYjCTgwEUvE9WThEaHy1J3RjyMA4ZBQmrR9hw1K"
    }
  ],
  "finalizationData":{
      "finalizationIndex":3,
      "finalizers":[
         {
            "bakerId":0,
            "signed":true,
            "weight":1200000000135
         },
         {
            "bakerId":1,
            "signed":false,
            "weight":800000000005
         },
         {
            "bakerId":2,
            "signed":false,
            "weight":1200000000000
         },
         {
            "bakerId":3,
            "signed":true,
            "weight":800000000000
         },
         {
            "bakerId":4,
            "signed":true,
            "weight":1200000000000
         }
      ],
      "finalizationDelay":0,
      "finalizationBlockPointer":"847e0c5037f8eedf3e5b5c932e4ebcb0b5ad9deaa986d83a165d8712594e0e1d"
   },
  "transactionSummaries": [
    {
      "hash": "d1aeaedec44266f044a230ad7bd9339a992418fbcd11a3217686f6854a1816cd",
      "sender": null,
      "cost": 0,
      "energyCost": 35000,
      "result": {
        "events": [
          {
            "tag": "AccountCreated",
            "contents": "3ADz9qYiEzeui5ccMC7CCHrdsWArV4T45ktGhyt2CnUK4BL4U6"
          },
          {
            "tag": "CredentialDeployed",
            "regId": "a65da3c626172056bfb0f6612bf76bd79acf80dee092b0394b93cfabaa500b727592af22f66fae834965d33fda8940f1",
            "account": "3ADz9qYiEzeui5ccMC7CCHrdsWArV4T45ktGhyt2CnUK4BL4U6"
          }
        ],
        "outcome": "success"
      },
      "type": null,
      "index": 0
    },
    {
      "hash": "4b7e1b22ff9365e29c57d7f85a0fd7a7dd3c50245cb9d04c560c520298013c3f",
      "sender": "43TULx3kDPDeQy1C1iLwBbS5EEV96cYPw5ZRdA9Dm4D23hxGZt",
      "cost": 165,
      "energyCost": 165,
      "result": {
        "events": [
          {
            "amount": 1000000,
            "tag": "Transferred",
            "to": {
              "address": "43TULx3kDPDeQy1C1iLwBbS5EEV96cYPw5ZRdA9Dm4D23hxGZt",
              "type": "AddressAccount"
            },
            "from": {
              "address": "43TULx3kDPDeQy1C1iLwBbS5EEV96cYPw5ZRdA9Dm4D23hxGZt",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "type": "transfer",
      "index": 0
    },
    {
      "hash": "5292c68df8787b3b22a61397edc3fc04858d4112e770ee7674e80751254d6f27",
      "sender": "39KavYmY7LRw1mV5wbmTKY8A38ktzrQ3eWCn7KPzDW3S4sJps9",
      "cost": 59,
      "energyCost": 59,
      "result": {
        "outcome": "reject",
        "rejectReason": {
          "tag": "AmountTooLarge",
          "contents": [
            {
              "address": "39KavYmY7LRw1mV5wbmTKY8A38ktzrQ3eWCn7KPzDW3S4sJps9",
              "type": "AddressAccount"
            },
            200000000
          ]
        }
      },
      "type": "transfer",
      "index": 0
    },
    {
      "hash": "15c2c8a0a9d496630dff603d4d404a6912d96215755884522798092bc179de5b",
      "sender": "43TULx3kDPDeQy1C1iLwBbS5EEV96cYPw5ZRdA9Dm4D23hxGZt",
      "cost": 265,
      "energyCost": 265,
      "result": {
        "events": [
          {
            "tag": "StakeDelegated",
            "account": "43TULx3kDPDeQy1C1iLwBbS5EEV96cYPw5ZRdA9Dm4D23hxGZt",
            "baker": 0
          }
        ],
        "outcome": "success"
      },
      "type": "delegateStake",
      "index": 1
    },
    {
      "hash": "ae13d5677cdcbd90fad54e9768f4f1f4c44610c45af1c2ca0481119d47c8a2bb",
      "sender": "43TULx3kDPDeQy1C1iLwBbS5EEV96cYPw5ZRdA9Dm4D23hxGZt",
      "cost": 265,
      "energyCost": 265,
      "result": {
        "events": [
          {
            "tag": "StakeDelegated",
            "account": "43TULx3kDPDeQy1C1iLwBbS5EEV96cYPw5ZRdA9Dm4D23hxGZt",
            "baker": 0
          }
        ],
        "outcome": "success"
      },
      "type": "delegateStake",
      "index": 2
    },
    {
      "hash": "73513777db8519ef5b71a0bd06a1b06bd705bf06e62737fa563ed75e20fcec27",
      "sender": "43TULx3kDPDeQy1C1iLwBbS5EEV96cYPw5ZRdA9Dm4D23hxGZt",
      "cost": 3167,
      "energyCost": 3167,
      "result": {
        "events": [
          {
            "tag": "BakerAdded",
            "contents": 5
          }
        ],
        "outcome": "success"
      },
      "type": "addBaker",
      "index": 3
    },
    {
      "hash": "affc03c8211ea90cb72143e5c44eff7e55089668af8e64bd6b978ef7cfac39c7",
      "sender": "43TULx3kDPDeQy1C1iLwBbS5EEV96cYPw5ZRdA9Dm4D23hxGZt",
      "cost": 265,
      "energyCost": 265,
      "result": {
        "outcome": "reject",
        "rejectReason": {
          "tag": "InvalidStakeDelegationTarget",
          "contents": 12312312312
        }
      },
      "type": "delegateStake",
      "index": 4
    },
    {
      "hash": "2b40fc10934a371e9d23dead69435d834aa725ebc418b6631abb49b5f808a07c",
      "sender": "43TULx3kDPDeQy1C1iLwBbS5EEV96cYPw5ZRdA9Dm4D23hxGZt",
      "cost": 166,
      "energyCost": 166,
      "result": {
        "outcome": "reject",
        "rejectReason": {
          "tag": "SerializationFailure"
        }
      },
      "type": null,
      "index": 5
    },
    {
      "hash": "8841d4dd1da2875b63d829be55fc5441adba2efa2baaed3b1228601e25bc2bb2",
      "sender": "43TULx3kDPDeQy1C1iLwBbS5EEV96cYPw5ZRdA9Dm4D23hxGZt",
      "cost": 165,
      "energyCost": 165,
      "result": {
        "outcome": "reject",
        "rejectReason": {
          "tag": "SerializationFailure"
        }
      },
      "type": null,
      "index": 6
    },
    {
      "hash": "5257c01e5f42a0afcead07149a474162c2a193702de59177bff0d7b8812a4d09",
      "sender": "43TULx3kDPDeQy1C1iLwBbS5EEV96cYPw5ZRdA9Dm4D23hxGZt",
      "cost": 165,
      "energyCost": 165,
      "result": {
        "outcome": "reject",
        "rejectReason": {
          "tag": "InvalidBakerRemoveSource",
          "contents": "43TULx3kDPDeQy1C1iLwBbS5EEV96cYPw5ZRdA9Dm4D23hxGZt"
        }
      },
      "type": "removeBaker",
      "index": 7
    },
    {
      "hash": "2a0a5ea99e9f091a3704c7fa8d163e971f32d2a591060cdeab4a02790f7cf4ad",
      "sender": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
      "cost": 2705,
      "energyCost": 2705,
      "result": {
        "events": [
          {
            "tag": "ModuleDeployed",
            "contents": "69f895cec649178d771b016019912e84bbc659ef35e132585cb5a358b7f7ffb0"
          }
        ],
        "outcome": "success"
      },
      "type": "deployModule",
      "index": 0
    },
    {
      "hash": "0b04e5f0e2969ea2961cc0667d48cc17166f3ad84e1cd5900d85d79e63919bd3",
      "sender": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
      "cost": 1527,
      "energyCost": 1527,
      "result": {
        "events": [
          {
            "tag": "ModuleDeployed",
            "contents": "33f8832053c36b443084040537f11a66527bc1446a0aa41704ddf06e44093455"
          }
        ],
        "outcome": "success"
      },
      "type": "deployModule",
      "index": 1
    },
    {
      "cost": 3031,
      "energyCost": 3031,
      "hash": "0a75fdac33df28b8ae17fead28f837cb28ae23999cdb81bd5f9b7993e24cc204",
      "index": 0,
      "result": {
        "events": [
          {
            "address": {
              "index": 0,
              "subindex": 0
            },
            "amount": 0,
            "name": 200,
            "ref": "7d6b63bde558564b77070bf1da85c56e7fd9f006ef8d0923d19689577614dd2d",
            "tag": "ContractInitialized"
          }
        ],
        "outcome": "success"
      },
      "sender": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
      "type": "initContract"
    },
    {
      "hash": "a633a418a26353989dec0e813353984892976e3c821bfac5cddee9850ce7bf9e",
      "sender": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
      "cost": 464,
      "energyCost": 464,
      "result": {
        "events": [
          {
            "amount": 10,
            "tag": "Updated",
            "instigator": {
              "address": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
              "type": "AddressAccount"
            },
            "address": {
              "subindex": 0,
              "index": 0
            },
            "message": "ExprMessage (Let (LetForeign (Imported 7d6b63bde558564b77070bf1da85c56e7fd9f006ef8d0923d19689577614dd2d (Name 130)) (Linked (Constructor (Name 130))) (Atom (BoundVar (Reference (-1))))) (Let (Constructor (Name 1)) (App (Reference 0) [BoundVar (Reference 1)])))"
          }
        ],
        "outcome": "success"
      },
      "type": "update",
      "index": 0
    }
  ]
}
"""


getBlockSummaryContractDeploysStub =
    """
{
  "specialEvents": [
    {
      "bakerId": 3,
      "rewardAmount": 35984,
      "bakerAccount": "4EbkxwtSCopq6U1d7FcRgugR4DvKin4Wyg2qW5wmDkvWYFmDca"
    }
  ],
  "transactionSummaries": [
    {
      "hash": "2a0a5ea99e9f091a3704c7fa8d163e971f32d2a591060cdeab4a02790f7cf4ad",
      "sender": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
      "cost": 2705,
      "energyCost": 2705,
      "result": {
        "events": [
          {
            "tag": "ModuleDeployed",
            "contents": "69f895cec649178d771b016019912e84bbc659ef35e132585cb5a358b7f7ffb0"
          }
        ],
        "outcome": "success"
      },
      "type": "deployModule",
      "index": 0
    },
    {
      "hash": "0b04e5f0e2969ea2961cc0667d48cc17166f3ad84e1cd5900d85d79e63919bd3",
      "sender": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
      "cost": 1527,
      "energyCost": 1527,
      "result": {
        "events": [
          {
            "tag": "ModuleDeployed",
            "contents": "33f8832053c36b443084040537f11a66527bc1446a0aa41704ddf06e44093455"
          }
        ],
        "outcome": "success"
      },
      "type": "deployModule",
      "index": 1
    },
    {
      "hash": "21585869b20629a5fb13eaa40e4d488e6c458d8609e994194b6c4c0cd78ded50",
      "sender": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
      "cost": 1365,
      "energyCost": 1365,
      "result": {
        "events": [
          {
            "tag": "ModuleDeployed",
            "contents": "73310b972c101c4ec69e6eb427ebc843d5483f4adb771d1dc711f8de5ebaced4"
          }
        ],
        "outcome": "success"
      },
      "type": "deployModule",
      "index": 2
    },
    {
      "hash": "b5fba16ba8bb959bab172beb8939700e28d043689e6fd08023034d3a2e3d5168",
      "sender": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
      "cost": 1558,
      "energyCost": 1558,
      "result": {
        "events": [
          {
            "tag": "ModuleDeployed",
            "contents": "73e1ebc954909b336a9c08443fff079e75956e7c0f314c4ad56b8bcfebaef8c4"
          }
        ],
        "outcome": "success"
      },
      "type": "deployModule",
      "index": 3
    },
    {
      "hash": "e91402ac563df428372a23ab83a26224696d89c14d8ab1f69623f5ca05efce98",
      "sender": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
      "cost": 4890,
      "energyCost": 4890,
      "result": {
        "events": [
          {
            "tag": "ModuleDeployed",
            "contents": "3aa516e0b15327d7427b9acf7600c3e0376f65eeef7187975be38df70e0ab3e6"
          }
        ],
        "outcome": "success"
      },
      "type": "deployModule",
      "index": 4
    },
    {
      "hash": "bac1fb11f121a88431c146acf2b5514cb723629d553f384b1c9691470b7648fe",
      "sender": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
      "cost": 657,
      "energyCost": 657,
      "result": {
        "events": [
          {
            "tag": "ModuleDeployed",
            "contents": "6a1ece5ea0d5a25bcf6e53f6e7bb4cf2b5a8cabaa8b58ba30a454e3582b26007"
          }
        ],
        "outcome": "success"
      },
      "type": "deployModule",
      "index": 5
    },
    {
      "hash": "7df554bb85448d8cc2cc9ed11b9eac348f56105e408ffb34c987c1781cc7bace",
      "sender": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
      "cost": 1417,
      "energyCost": 1417,
      "result": {
        "events": [
          {
            "tag": "ModuleDeployed",
            "contents": "ec79b0b4ab8f91247b271af307e8d0ae7f8c6cff7bcd9ca63d214116a01aa876"
          }
        ],
        "outcome": "success"
      },
      "type": "deployModule",
      "index": 6
    },
    {
      "hash": "404311b6f25efff2320d5091651e13745a078898e465e2bc006b4cad1c9341b0",
      "sender": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
      "cost": 3055,
      "energyCost": 3055,
      "result": {
        "events": [
          {
            "tag": "ModuleDeployed",
            "contents": "7d6b63bde558564b77070bf1da85c56e7fd9f006ef8d0923d19689577614dd2d"
          }
        ],
        "outcome": "success"
      },
      "type": "deployModule",
      "index": 7
    },
    {
      "hash": "7c1dac909a4f49a74d80976467eecbbe641f142197747dd5e470f22167641474",
      "sender": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
      "cost": 3479,
      "energyCost": 3479,
      "result": {
        "events": [
          {
            "tag": "ModuleDeployed",
            "contents": "1e4a518694fba2bd3edecec2aaac166edf2b65b59c0c6900e26637b73a7fbb2b"
          }
        ],
        "outcome": "success"
      },
      "type": "deployModule",
      "index": 8
    },
    {
      "hash": "4aa521cb1733ef27a78151d698a8c460c69af9f2a4d4619497b7cea73a11264f",
      "sender": "3LqzxroRTxGGBuhyoH5CzSyUvrgvhX1tPPCLVZz8QQ9ZmbrmcZ",
      "cost": 1775,
      "energyCost": 1775,
      "result": {
        "events": [
          {
            "tag": "ModuleDeployed",
            "contents": "6e33fddc0a95324af4510964827c02c87cf403255cb8f7baae90786625133a3a"
          }
        ],
        "outcome": "success"
      },
      "type": "deployModule",
      "index": 9
    }
  ]
}
  """


getBlockSummaryFailureStub =
    """
  {
    "specialEvents": [
      {
        "bakerId": 2,
        "rewardAmount": 1751,
        "bakerAccount": "3fS4u95Sx9SKzU83kxxYP4SWaWirVix4T7P9bgswmceqvcs4vR"
      }
    ],
    "transactionSummaries": [
      {
        "hash": "0ada4e64558bb99a3607647c490f39083f44c709e654d689d8bf3fb343a95961",
        "sender": "43TULx3kDPDeQy1C1iLwBbS5EEV96cYPw5ZRdA9Dm4D23hxGZt",
        "cost": 165,
        "result": {
          "outcome": "reject",
          "rejectReason": {
            "tag": "InvalidAccountReference",
            "contents": "3Es2U5gMdKrqJdXSUVzgW4KUosJ91AxfsAuvKx5tKE9P2SvjVk"
          }
        },
        "energyCost": 165,
        "type": "transfer",
        "index": 0
      }
    ]
  }
  """


getBlockSummaryResponseStub =
    """
{
  "specialEvents": [
    {
      "bakerId": 4,
      "rewardAmount": 207,
      "bakerAccount": "4c7SXWg5bD3YpWQ2mmS8DSQiFm9MRpTd7Novo4ESPb1QLSYrts"
    }
  ],
  "transactionSummaries": [
    {
      "hash": "ae3154e1ee8a64d9e9718e57fbc979175be2ee8526b23fcddab2d626ebaeb72d",
      "sender": null,
      "cost": 0,
      "result": {
        "events": [
          {
            "tag": "AccountCreated",
            "contents": "3P2Qsi8FeMB6AijMi3kpD9FrcFfAkoHDMu8kf7Fbd3cYYJpk2s"
          },
          {
            "tag": "CredentialDeployed",
            "regId": "ac64aac1da15afd90d185475705935fbe224d5f7ddc43988e7db511656c787b452820b5096a2b323cf7612f5609d4cfb",
            "account": "3P2Qsi8FeMB6AijMi3kpD9FrcFfAkoHDMu8kf7Fbd3cYYJpk2s"
          }
        ],
        "outcome": "success"
      },
      "energyCost": 35000,
      "type": null,
      "index": 0
    },
    {
      "hash": "2ecde309ea6b48cebfbb73eb1ee3364c4f10330955a4a13acb7d87076461ab2d",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "dba5e4bafc7d2201cc23d30f288e276b5305b0722a74d0ac1fe1f6b15d1496a2",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "f59897e5be69ecd5ed5843a10d74ee2b652064bd5077b853e6b324c23683af7b",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "f49899ac815b01a9f6e49c4d1fc926c511fcd3cc453c1307a504ef937a4fe8b5",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressContract"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "3ad7e0a0e3ed193bfba065c83704ae5bf84837255ac720565479afab81767c96",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressContract"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "d3b0cdeab57dc4d5e6b1faa1e4915ddfc2d025655775254e7124ae031688d9d8",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "bf6e33703977ce94caa918911f63b04654da0047454c484be9c80b487cc142c5",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "8781b249f4629f0ca9789fe143bfd4031208a7bfcca0ade9dd9f63ae8dac317d",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "41e6c23be80ab1151697ad16a4427268b0fd5440af0bb7bee4b330648669b164",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "71b1e81a467f038102b4028f62f1d75324b3f523472b89c583fdac918e762560",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "5298e7d571852da5c030c15b1513405c365111315efbc062a9d0f9082d1d5e6f",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "c7487dc3ee7cd097636badc9c21771d2a62a37052be8204078f516583cb5320e",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "dd6871001af51dc048bbae8ceb187c58fb2cf66ba838897b8f527642fb7e552a",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "fc2ee2cd1294f0dc8a0c738c25bc6f762edf2689ee37b22382d9a4b931637ae7",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "029681010cdc89383926d32017af7e51357f66b33f1527396f0af63b5b9a3e6c",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "64fbd260407f681292cc4931f8c3d7edb034574c172a90f1923188751fb6775a",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "5cc3ec13c9844456d8b65f0534dca943a4ece1b12c1ca0f8f5a2936c7e260722",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "5a9c8dd2b90b7943a4891b1ab41cbe8ae13cefb7a91c7ef3d884201408352b04",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "16672379084db2866db4564e0c42103d3f6edcdfedee6b9ce5f520b9aef78ea7",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    },
    {
      "hash": "de7eecba63d94c7810126cc325d6cf43d9382d8d2fed680202140fe97e91fe76",
      "sender": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
      "cost": 10,
      "result": {
        "events": [
          {
            "amount": 123,
            "tag": "Transferred",
            "to": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            },
            "from": {
              "address": "4KYJHs49FX7tPD2pFY2whbfZ8AjupEtX8yNSLwWMFQFUZgRobL",
              "type": "AddressAccount"
            }
          }
        ],
        "outcome": "success"
      },
      "energyCost": 10,
      "type": "transfer"
    }
  ]
}
"""


{-| This block summary response was used to test that unusally long words
in the transaction memo of an event are displayed correctly.
-}
getBlockSummaryLongMemoStub =
    """    
    {
        "finalizationData": {
            "finalizationIndex": 40851,
            "finalizers": [
                {
                    "bakerId": 0,
                    "signed": true,
                    "weight": 3000000000000
                },
                {
                    "bakerId": 1,
                    "signed": true,
                    "weight": 3000000000000
                },
                {
                    "bakerId": 2,
                    "signed": true,
                    "weight": 3000000000000
                },
                {
                    "bakerId": 3,
                    "signed": true,
                    "weight": 3000000000000
                },
                {
                    "bakerId": 4,
                    "signed": true,
                    "weight": 3000000000000
                },
                {
                    "bakerId": 15,
                    "signed": true,
                    "weight": 300292749406
                },
                {
                    "bakerId": 42,
                    "signed": false,
                    "weight": 300143881109
                }
            ],
            "finalizationDelay": 0,
            "finalizationBlockPointer": "e784294b2393ceedc1f5c8d9169591bd99dedc0564b8362852a2990f0cebfe00"
        },
        "specialEvents": [
            {
                "tag": "Mint",
                "foundationAccount": "48RDnoQaCKwy8xteebgLCDdX8qACa3WB5GnfuGMpCDfB2UfdL4",
                "mintPlatformDevelopmentCharge": "138171",
                "mintFinalizationReward": "414508",
                "mintBakingReward": "829017"
            },
            {
                "remainder": "5",
                "tag": "FinalizationRewards",
                "finalizationRewards": [
                    {
                        "amount": "79711",
                        "address": "3c1hZst6hfxm5CMPYGmUw7LvMe3Mo1VwgkXrBAb59GSdLzPiSz"
                    },
                    {
                        "amount": "79711",
                        "address": "3uyRpq2NPSY4VJn8Qd1uWGcUQTGpCAarHTtqpneiSGqv36Uhna"
                    },
                    {
                        "amount": "79711",
                        "address": "4AymJeLgpB7s7bSn6ARm22iAB15m5PpTHaXATBCktnzxvoBowJ"
                    },
                    {
                        "amount": "7974",
                        "address": "4C9vCCSLdeTB2DsUZZECReygdLbMR5AACoR1H7EfBfYem7bqLx"
                    },
                    {
                        "amount": "79711",
                        "address": "4ESt5DAQY3xi74Pj386otNf2S4fsohDG8Qxyv15hvqvbgFvYvC"
                    },
                    {
                        "amount": "7978",
                        "address": "4LRhqFikMSWMzX6ZenkvRVn94H6Zu6HdxmHvap9cuHmMrPraV2"
                    },
                    {
                        "amount": "79711",
                        "address": "4M63wWygknpRd1hVuKoirtusZJbWE9wiFe3rXCrZcFgLzXYzh4"
                    }
                ]
            },
            {
                "tag": "BlockReward",
                "bakerReward": "41914",
                "newGASAccount": "42737",
                "baker": "4M63wWygknpRd1hVuKoirtusZJbWE9wiFe3rXCrZcFgLzXYzh4",
                "foundationAccount": "48RDnoQaCKwy8xteebgLCDdX8qACa3WB5GnfuGMpCDfB2UfdL4",
                "oldGASAccount": "1671",
                "foundationCharge": "9220",
                "transactionFees": "92200"
            }
        ],
        "updates": {
            "chainParameters": {
                "minimumThresholdForBaking": "300000000000",
                "rewardParameters": {
                    "mintDistribution": {
                        "mintPerSlot": 7.555665e-10,
                        "bakingReward": 0.6,
                        "finalizationReward": 0.3
                    },
                    "transactionFeeDistribution": {
                        "gasAccount": 0.45,
                        "baker": 0.45
                    },
                    "gASRewards": {
                        "chainUpdate": 5.0e-3,
                        "accountCreation": 2.0e-3,
                        "baker": 0.25,
                        "finalizationProof": 5.0e-3
                    }
                },
                "microGTUPerEuro": {
                    "denominator": 1,
                    "numerator": 100000000
                },
                "foundationAccountIndex": 5,
                "accountCreationLimit": 10,
                "bakerCooldownEpochs": 1,
                "electionDifficulty": 2.5e-2,
                "euroPerEnergy": {
                    "denominator": 1000000,
                    "numerator": 1
                }
            },
            "keys": {
                "rootKeys": {
                    "keys": [
                        {
                            "verifyKey": "e0b5fc074eef1178e41f6f2c494bde78b65bd3f21c36db4d41a1e6cb259c3a7d",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "1f420ab84863a9ba0472bcb39bfe27a07727f84ace50a6c3f9d6d75e2519febc",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "95a5064980b5bc27f3ae96a4831f3c60be82c2c0ee36de3ff028137a99fe823f",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "ef3e58b13c43a8439046a774290a8ef0b17d6fe516cea1f48de894a5aec669a4",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "830ac28b779ab09d0be9bd15ded7343be1f24df01ccf2e7cffd7d6359500f46c",
                            "schemeId": "Ed25519"
                        }
                    ],
                    "threshold": 3
                },
                "level2Keys": {
                    "mintDistribution": {
                        "threshold": 3,
                        "authorizedKeys": [
                            17,
                            18,
                            19,
                            20,
                            21
                        ]
                    },
                    "addAnonymityRevoker": {
                        "threshold": 3,
                        "authorizedKeys": [
                            37,
                            38,
                            39,
                            40,
                            41
                        ]
                    },
                    "transactionFeeDistribution": {
                        "threshold": 3,
                        "authorizedKeys": [
                            22,
                            23,
                            24,
                            25,
                            26
                        ]
                    },
                    "bakerStakeThreshold": {
                        "threshold": 3,
                        "authorizedKeys": [
                            32,
                            33,
                            34,
                            35,
                            36
                        ]
                    },
                    "microGTUPerEuro": {
                        "threshold": 1,
                        "authorizedKeys": [
                            11
                        ]
                    },
                    "protocol": {
                        "threshold": 2,
                        "authorizedKeys": [
                            5,
                            6,
                            7
                        ]
                    },
                    "addIdentityProvider": {
                        "threshold": 3,
                        "authorizedKeys": [
                            42,
                            43,
                            44,
                            45,
                            46
                        ]
                    },
                    "paramGASRewards": {
                        "threshold": 3,
                        "authorizedKeys": [
                            27,
                            28,
                            29,
                            30,
                            31
                        ]
                    },
                    "emergency": {
                        "threshold": 3,
                        "authorizedKeys": [
                            0,
                            1,
                            2,
                            3,
                            4
                        ]
                    },
                    "keys": [
                        {
                            "verifyKey": "97e908ee3a4d8dff49830aacca6bf42997f68afc1851fb5b3d58ae143ba4e147",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "f222cc7e2ec7bc1ba7abeca6f503a123abd244292809f04425ad8d72f6ef47ff",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "e098e1e55b13988b01e882a7fce5070fd12fa72d409eccebfbad0fb32d6ee057",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "58f71ef93d95fd9466aa917d426970c96ff48f9cf1aafb52e4caf427cf6331c8",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "9521707ac0ed5b577bc334c25154ab92336a1731bc9bcaefd14cd62bb42dcf96",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "38e5321fca15c1f87fe7c1e266f1e85f68a877e3eea11fa45063ad5e4b92e2fb",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "0aab1d7d1b81b7526163df81288f645249a0310f8ac84c5e8bc8f7a80be43df1",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "74aa4e9dac2bdfea7db5b9fccf240be370746a172a6ae2775b9751d96226dc9d",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "4a00ab5a36d4b402ddc4c3160df838f0aba805bb47843e85c8b14971a322f7b0",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "a0b17ad7ab31a49168ab4ee479141a2a102d34ee50c1e5abb3b2e78e901760ae",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "701376912e8820d404bd93e887d450e115e1dba9c53fdbe4e963ac3be92b508e",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "aa5dd0d777e21571ea6bca6fad39cf84e4655643913d83f6ba4da4552f07c3ec",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "88766292b604ec67298b817395bb41459575b7eebe22db49a3c87c6e664f67bd",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "3f14ba2f24bbb5fb0ec906e7b5080dd104bc7b0ffbf183234db67ab0ccaeec26",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "c39edc29fbf11264c60439e202a0a7fa91047fd54808057be50307a12018a38c",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "5b85a0fed564bab70b67d201f405fbdf2712498720e2c7de8aa81bce7258319a",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "dae562dbf3c082ff4ef58b3308b8858bb2fe105680ad863901776cc5f3131f3d",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "5f28823bd52e6bd86d760a8b104bbd4e3b50cf45dfb076f057ab0561756664a7",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "d034a8912eeef4c473798e0f790a16612781fb93b286baf20f4553fd07d8e1ca",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "e68b20b846c2144d1719f09613ad927055420f7d03282be8c1f0ec32d0a0837e",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "bf0c98b711d4bc5f0f2b90d427656234d2d4dc12bca59ae4c931cd9fcd4f66c0",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "97e0c06300746dd211f7aa2c29f3628c53036eba3c16a9ad1e116d5b09176ae5",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "10de8b005647c3fa2d528c21a1222ff8e2f7f10143e1d1f99f572016c150cdb5",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "f8a6f0e1b60caddfdfad28f2ebbe20393a9961ac5a02dd5770dfb4bc2f633d07",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "17cb31e51c9197ba1b88231f75ece5b3d33df60898408fac57375971bb68dfad",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "661cb015b7ac83ec349f5010d9f73a62f383d9bc14d3256600ba6d26f9042110",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "840d332eae5d251094e443a5a0acce58b63c43e72c7ce60add97f211d9b8b198",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "55e9a120150626468f029dd343c2b03eb97b8fb6228a5d8772028f8752ad40f2",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "4d60696102711d5e536c202a46f149ba8a959a49edf9be8da726a51d2f1185a7",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "aa0f8e391f16bd7095b1a3c02ba513a111194d650a7104a627bcbbf6c63d82c1",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "8c335e4bc9b8751ac45b15f3b1afea9765051f22393e93f5ff1bfd436d59c4f7",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "a5a77daa690591d7e44520303efc843ba359deddcfa89456ab1a7c5a26419696",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "e33274cbb31675f479ddff48a163924269cb46b99d814363d66948ccaf3d01f9",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "f2eb7342f2dfccbbe15f5f91adda221286b25447a5af8a8db2170d842a5c1350",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "cb9b6265f58cafc94bb33210357ee2709f4535b1aab08852d6df7a2421d1cb94",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "e26018620b19e90ab8a1a34e6d9d87d851e3f6f9d75f5f5192a30d3aec22f812",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "ce2cf1c1082b082abdb4599e15f6303303cc00cb8fe6820c5cda66c443e4144d",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "cd735b34b9ebd6d5dcb9cb56040b78e04a5a9449de2473a03887cf6dade2af60",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "78f9eac5476dd188177ddf22793c73231ff0abe11614f8373f86f33a2e14fbe6",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "802af182e7ba273d1c41441716c21db4773e4635fe1ea27760f33f3ad920eb0c",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "a264dd70a3eeac72397cde270806bb36651f25c1971d7a364a87b8d2184ebce0",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "951a1a3c5f3907f5706a9a587516cca3c13d8af21abceb4225df66d942d06f02",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "285568e67384368b0740309827a295a7c6044db1e7c96f6895c8fc7e2a5b4a38",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "bdb46f6cdcf24c5f0f183275c6325ea4034ce3bab1e7a362fce227d37c43e71f",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "9b86c0d98a295a23c3c92cb918a48d9b3cf3ab01d5d1d78a036e4a6b7d577c74",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "cb7ac7662b4dc4ea902e0d6116dd936ac4e1ace0a86e50059941aba6fd4aefc0",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "f69e41a6d9d8417db5497ebe4688b734fb709ee16bed147ded80dfa2930d69db",
                            "schemeId": "Ed25519"
                        }
                    ],
                    "foundationAccount": {
                        "threshold": 3,
                        "authorizedKeys": [
                            12,
                            13,
                            14,
                            15,
                            16
                        ]
                    },
                    "electionDifficulty": {
                        "threshold": 2,
                        "authorizedKeys": [
                            8,
                            9,
                            10
                        ]
                    },
                    "euroPerEnergy": {
                        "threshold": 2,
                        "authorizedKeys": [
                            8,
                            9,
                            10
                        ]
                    }
                },
                "level1Keys": {
                    "keys": [
                        {
                            "verifyKey": "0d57ecfe1f7d941fbc1bc0d001b632052d549cbeab6a966f944e3ad2dac89f6d",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "d0d29ce95287f45da364cdd6db512a9eb2bc43704381fc4cf0ffe14540568edc",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "94bec66e5b2f69ba94592c98a7facb78033d35c326beecaf263aef536d2a9c2f",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "1d13c5e8ca89c4fc0ef7e56e3bcec776490eb364a687c0769540fe2d59fc1b2c",
                            "schemeId": "Ed25519"
                        },
                        {
                            "verifyKey": "e9f9715686673769091df75ed0579976b82e83f73cc3559748c2e9627014d6d8",
                            "schemeId": "Ed25519"
                        }
                    ],
                    "threshold": 3
                }
            },
            "updateQueues": {
                "mintDistribution": {
                    "nextSequenceNumber": 1,
                    "queue": []
                },
                "rootKeys": {
                    "nextSequenceNumber": 1,
                    "queue": []
                },
                "addAnonymityRevoker": {
                    "nextSequenceNumber": 1,
                    "queue": []
                },
                "transactionFeeDistribution": {
                    "nextSequenceNumber": 1,
                    "queue": []
                },
                "bakerStakeThreshold": {
                    "nextSequenceNumber": 1,
                    "queue": []
                },
                "level2Keys": {
                    "nextSequenceNumber": 1,
                    "queue": []
                },
                "microGTUPerEuro": {
                    "nextSequenceNumber": 1,
                    "queue": []
                },
                "protocol": {
                    "nextSequenceNumber": 2,
                    "queue": []
                },
                "addIdentityProvider": {
                    "nextSequenceNumber": 1,
                    "queue": []
                },
                "gasRewards": {
                    "nextSequenceNumber": 1,
                    "queue": []
                },
                "foundationAccount": {
                    "nextSequenceNumber": 1,
                    "queue": []
                },
                "electionDifficulty": {
                    "nextSequenceNumber": 1,
                    "queue": []
                },
                "euroPerEnergy": {
                    "nextSequenceNumber": 1,
                    "queue": []
                },
                "level1Keys": {
                    "nextSequenceNumber": 1,
                    "queue": []
                }
            }
        },
        "transactionSummaries": [
            {
                "hash": "1623fb1b65720bbf34b7d9c47818af49e7c4610eaf6f1e241ba1208d1e5d94bb",
                "sender": "4PXJrvKGKb1YZt2Vua3mSDThqUU2EChweuydsFtVFtvDDr585H",
                "cost": "92200",
                "energyCost": 922,
                "result": {
                    "events": [
                        {
                            "amount": "1000000",
                            "tag": "Transferred",
                            "to": {
                                "address": "48RDnoQaCKwy8xteebgLCDdX8qACa3WB5GnfuGMpCDfB2UfdL4",
                                "type": "AddressAccount"
                            },
                            "from": {
                                "address": "4PXJrvKGKb1YZt2Vua3mSDThqUU2EChweuydsFtVFtvDDr585H",
                                "type": "AddressAccount"
                            }
                        },
                        {
                            "memo": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                            "tag": "TransferMemo"
                        }
                    ],
                    "outcome": "success"
                },
                "type": {
                    "contents": "transferWithMemo",
                    "type": "accountTransaction"
                },
                "index": 0
            }
        ]
    }
    """
