import * as path from 'path';
import * as express from 'express';
import { Router } from 'express';

export function staticsRouter(nodesSummary) {
  const router = Router();
  const publicPath = path.join(__dirname, '..', '..', '..', 'public');

  // All the assets are in "public" folder (Done by Webpack)
  router.use(express.static(publicPath));

  router.post('/post/nodes', function(request, response){
    nodesSummary[request.body.nodeName] = request.body;
    response.status(200).end()
  });

  // Any route should render the web app html (Generated by Webpack)
  router.get('**', (req, res) =>
    res.sendFile(path.join(publicPath, 'index.html')),
  );

  return router;
}
