import * as path from 'path'
import * as express from 'express'

export default () => {
  const router = express.Router()

  router.use(express.json()) // TODO(mbo) Do we need this?

  const publicPath = path.join(__dirname, '..', '..', '..', 'public')

  // All the assets are in "public" folder (done by Webpack).
  router.use(express.static(publicPath))

  // Point any non-asset route to the app (generated by Webpack).
  router.get('**', (req, res) =>
    res.sendFile(path.join(publicPath, 'index.html'))
  )

  return router
}
